
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package inicio.flexycup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 8;
  public static final int PUNTO = 14;
  public static final int OR = 7;
  public static final int IGUAL = 16;
  public static final int MAYIGUAL = 19;
  public static final int ELIMINAR = 9;
  public static final int PARENC = 23;
  public static final int PARENA = 22;
  public static final int ID = 11;
  public static final int MEN = 21;
  public static final int AST = 13;
  public static final int NUM = 10;
  public static final int VALORES = 4;
  public static final int STRING = 15;
  public static final int COMA = 12;
  public static final int MENIGUAL = 18;
  public static final int INSERT = 3;
  public static final int EOF = 0;
  public static final int SELEC = 2;
  public static final int error = 1;
  public static final int MAY = 20;
  public static final int EN = 5;
  public static final int PCOMA = 17;
  public static final int FILT = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELEC",
  "INSERT",
  "VALORES",
  "EN",
  "FILT",
  "OR",
  "AND",
  "ELIMINAR",
  "NUM",
  "ID",
  "COMA",
  "AST",
  "PUNTO",
  "STRING",
  "IGUAL",
  "PCOMA",
  "MENIGUAL",
  "MAYIGUAL",
  "MAY",
  "MEN",
  "PARENA",
  "PARENC"
  };
}

