/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package inicio.view;

import inicio.utils.OpenClosedFiles;
import static inicio.view.Inicio.frame;
import static inicio.view.Inicio.tabbed1;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author tuxrex
 */
public class Files extends javax.swing.JPanel {

    NumeroLinea num;
    //public static boolean isSave = false;

    public static boolean modificado;
    Files f;

    public Files() {
        initComponents();
        num = new NumeroLinea(areaCode);
        jScrollPane1.setViewportView(areaCode);
        //jScrollPane.setViewportView(textPane);
        jScrollPane1.setRowHeaderView(num);
        areaCode.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                modificado = true;
            }

            public void removeUpdate(DocumentEvent e) {
                modificado = true;
            }

            public void changedUpdate(DocumentEvent e) {
                modificado = true;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaCode = new javax.swing.JTextPane();
        cerrar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        newFile = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        areaCode.setFont(new java.awt.Font("Liberation Sans", 0, 19)); // NOI18N
        jScrollPane1.setViewportView(areaCode);

        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        newFile.setText("Nuevo Archivo");
        newFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(415, Short.MAX_VALUE)
                .addComponent(cerrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newFile, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed

        if (!modificado) {

            inicio.Principal.i.tabbed1.remove(inicio.Principal.i.tabbed1.getSelectedIndex());

        } else {
            int opcion = JOptionPane.showOptionDialog(null, "¿Deseas cerrar sin guardar cambios?", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Sí", "No"}, "No");
            if (opcion == JOptionPane.YES_OPTION) {
                inicio.Principal.i.tabbed1.remove(inicio.Principal.i.tabbed1.getSelectedIndex());

            } else if (opcion == JOptionPane.NO_OPTION) {

            }
        }

    }//GEN-LAST:event_cerrarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        String code = areaCode.getText();
        String path = Inicio.ruta;
        String newPath = path + "/" + Inicio.nombre;
        String pathOrigin = Inicio.iscreates ? path : newPath;
        System.out.println("Path de Guardar " + pathOrigin);
        try {
            OpenClosedFiles.guardarArchivo(code, newPath);
            JOptionPane.showMessageDialog(null, "Guardado correctamente");
            Inicio.iscreates = false;
            modificado = false;

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se pudo guardar el archivo");
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void newFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileActionPerformed

        String path = Inicio.ruta;
        System.out.println("Ruta dentro del Nuevo: " + path);
        String nombre = JOptionPane.showInputDialog("Ingrese el nombre del archivo");
        String newPath = path + "/" + nombre + OpenClosedFiles.extension;
        String Original = Inicio.isnew ? path : newPath;

        try {
            if (nombre != null) {
                OpenClosedFiles.createFile(newPath);
                JOptionPane.showMessageDialog(null, "Archivo creado correctaente con el nombre de: " + nombre);
                String[] update = path.split("/");
                System.out.println("Ruta dentro del Nuevo: " + newPath);
                Inicio.Arbol(update);

                Inicio.arbolDirectorio.updateUI();

                //f=new Files();
                //Inicio.tabbed1.addTab(nombre+".txt", Inicio.frame);
                // Inicio.tabbed1.setSelectedComponent(tabbed1.getComponent(tabbed1.getSelectedIndex()));
                Inicio.isnew = false;
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se ha podido crear el archivo");
        }


    }//GEN-LAST:event_newFileActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        String code = areaCode.getText();
        String path = Inicio.ruta;
        String newPath = path + "/" + Inicio.nombre;
        try {
            // String pathOrigin = Inicio.iscreates ? path : newPath;
            OpenClosedFiles.eliminarArchivo(newPath);
            String update[] = path.split("/");
            Inicio.Arbol(update);
            Inicio.arbolDirectorio.updateUI();
            JOptionPane.showMessageDialog(null, "Eliminado correctamente");
        } catch (IOException ex) {
            System.out.println("Hubo problemas al eliminar el archivo");
        }
    }//GEN-LAST:event_eliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextPane areaCode;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newFile;
    // End of variables declaration//GEN-END:variables
}
