/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inicio.view;

import inicio.utils.OpenClosedFiles;
import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileFilter;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;

/**
 *
 * @author tuxrex
 */
public class Inicio extends javax.swing.JFrame {

    public static boolean iscreates = false;

    /**
     * Creates new form Inicio
     */
    File ficheroExt;
    Files frame;
    public static String ruta="";
    public static String nombre="";

    public Inicio() {
        initComponents();

        arbolDirectorio.addTreeSelectionListener(new TreeSelectionListener() {
 

            @Override
            public void valueChanged(TreeSelectionEvent tse) {
                try {
                    //arbolDirectorio.getLastSelectedPathComponent().toString();
                    String archivo = arbolDirectorio.getLastSelectedPathComponent().toString();
                    frame = new Files();
                    //frame.setVisible(true);

                    if (archivo.contains(".")) {

                        tabbed1.addTab(archivo, frame);
                        tabbed1.setSelectedComponent(frame);
                        OpenClosedFiles.leerArchivo(ruta + "/" + tabbed1.getTitleAt(tabbed1.getSelectedIndex()));
                    nombre=archivo;
                       
                        System.out.println(tabbed1.getTitleAt(tabbed1.getSelectedIndex()));
                        System.out.println("Nombre: " + tabbed1.getTabCount());
                        System.out.println("Ruta de archivo seleccionado: " + ruta + "/" + tabbed1.getTitleAt(tabbed1.getSelectedIndex()));
          

                    }
                } catch (Exception e) {
                    //JOptionPane.showMessageDialog(null, "No se ha seleccionado la carpeta, vuelve a intentarlo");

                }

            }

        });


    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        pane1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbolDirectorio = new javax.swing.JTree();
        tabbed1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        openFile = new javax.swing.JMenuItem();
        newProject = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SQLemulator");

        arbolDirectorio.setFont(new java.awt.Font("Liberation Sans", 0, 17)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("-");
        arbolDirectorio.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(arbolDirectorio);

        javax.swing.GroupLayout pane1Layout = new javax.swing.GroupLayout(pane1);
        pane1.setLayout(pane1Layout);
        pane1Layout.setHorizontalGroup(
            pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
        );
        pane1Layout.setVerticalGroup(
            pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTextPane1.setFont(new java.awt.Font("Liberation Sans", 0, 19)); // NOI18N
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        jTextPane2.setFont(new java.awt.Font("Liberation Sans", 0, 19)); // NOI18N
        jTextPane2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextPane2KeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTextPane2);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel1.setText("Area de Consultas SQL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        file.setText("Archivo");
        file.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileMouseClicked(evt);
            }
        });
        file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileActionPerformed(evt);
            }
        });

        openFile.setIcon(new javax.swing.ImageIcon("/home/tuxrex/NetBeansProjects/Web/SQLemulator/src/main/java/inicio/icons/database.png")); // NOI18N
        openFile.setText("Abrir archivo");
        openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileActionPerformed(evt);
            }
        });
        file.add(openFile);

        newProject.setIcon(new javax.swing.ImageIcon("/home/tuxrex/NetBeansProjects/Web/SQLemulator/src/main/java/inicio/icons/add_9068662.png")); // NOI18N
        newProject.setText("CrearProyecto");
        newProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProjectActionPerformed(evt);
            }
        });
        file.add(newProject);

        jMenuBar1.add(file);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbed1, javax.swing.GroupLayout.DEFAULT_SIZE, 1259, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tabbed1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileActionPerformed

    }//GEN-LAST:event_fileActionPerformed

    private void fileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileMouseClicked

    }//GEN-LAST:event_fileMouseClicked

    private void openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileActionPerformed
        // TODO add your handling code here:
        //int seleccion=0;

        JFileChooser abrirDirectorio = new JFileChooser();
        abrirDirectorio.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int seleccion = abrirDirectorio.showOpenDialog(this);

        if (seleccion == abrirDirectorio.APPROVE_OPTION) {
            ficheroExt = abrirDirectorio.getSelectedFile();
            ruta = ficheroExt.getAbsolutePath();
            System.out.println("Ruta: " + ruta);
            String[] carp = ruta.split("/");

            Arbol(carp);

        } else {
            JOptionPane.showMessageDialog(null, "No se selecciono ninguna carpeta");
        }
    }//GEN-LAST:event_openFileActionPerformed

    private void jTextPane2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPane2KeyPressed
        System.out.println("Hola acaban de hacer enter");
    }//GEN-LAST:event_jTextPane2KeyPressed

    private void newProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProjectActionPerformed
                        String nombreCarpeta = JOptionPane.showInputDialog("Ingrese el nombre de la carpeta para el proyecto:");
                String nombreArchivo = JOptionPane.showInputDialog("Ingrese el nombre del archivo del proyecto:");

                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setDialogTitle("Selecciona la carpeta donde se creará el proyecto");
                fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

                int result = fileChooser.showOpenDialog(Inicio.this);

                if (result == JFileChooser.APPROVE_OPTION) {
                    File selectedFolder = fileChooser.getSelectedFile();
                    File carpetaProyecto = new File(selectedFolder, nombreCarpeta);
                    carpetaProyecto.mkdir();
                    ruta = OpenClosedFiles.crearArchivoProyecto(carpetaProyecto, nombreArchivo);
                    System.out.println("path elegido: " + ruta);
                    String rutas[] = ruta.split("/");
                    iscreates = true;
                    Arbol(rutas);
                }

    }//GEN-LAST:event_newProjectActionPerformed


    private void Arbol(String[] carp) {
        root = new DefaultMutableTreeNode(carp[3]);
        modelo = new DefaultTreeModel(root);
        Crear(root, carp);
        arbolDirectorio.setModel(modelo);

    }

    private void Crear(DefaultMutableTreeNode nodo, String[] carpi) {
        //File[] subfolder = carpeta.listFiles();
        DefaultMutableTreeNode childNode;
        String[] carp = carpi;

        File file;
        if (carp.length > 0) {
            //int cont=0;
            for (int i = 4; i < carp.length; i++) {
                file = new File(carp[i]);

                childNode = new DefaultMutableTreeNode(file.getName());
                modelo.insertNodeInto(childNode, nodo, 0);
                nodo = childNode;

            }
            if (!iscreates) {
                File[] ficheros = ficheroExt.listFiles();

                if (ficheros != null) {
                    for (File f : ficheros) {

                        childNode = new DefaultMutableTreeNode(f.getName());
                        modelo.insertNodeInto(childNode, nodo, 0);

                    }
                }

            }
                    //iscreates = false;

        }

    }
    /**
     * z
     *
     * @param args the command line arguments
     */
//    private List<File> carpetasAbiertas = new ArrayList<>();
    private DefaultMutableTreeNode root;
    private DefaultTreeModel modelo;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTree arbolDirectorio;
    private javax.swing.JMenu file;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JMenuItem newProject;
    private javax.swing.JMenuItem openFile;
    private javax.swing.JPanel pane1;
    public static javax.swing.JTabbedPane tabbed1;
    // End of variables declaration//GEN-END:variables
}
